baseURL = 'https://koalafionagao-ai.github.io/my_blogs/'
title = "Fiona's Blog"
theme = 'PaperMod'
defaultContentLanguage = 'en' # 默认全局语言设为英文

[params]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = true

# 多语言菜单配置
[languages]
    [languages.en]
        languageName = "English"
        weight = 1
    [languages.zh]
        languageName = "中文"
        languageCode = "zh-cn"
        weight = 2
        hasCJKLanguage = true # 针对中文的特殊优化（精准计算字数）